apiPrefix: /api
allowed-origin: http://localhost:4200

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotifygamedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: spotify.game13@gmail.com
    password: axjozfpzerrliumz
    protocol: smtp
    auth: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          from: spotify.game13@gmail.com
    debug: false

spotify:
  client:
    id: fde3d9ea0288450b928ab3858071e1c8
    secret: 557cacaaae254e4493485ebb7fb71a29

app:
  verification:
    url: http://localhost:8080/api/email/register-email
    location: http://localhost:4200
  user_password:
    url: http://localhost:8080/api/email/password-email
    location: http://localhost:4200/password/
  jwt:
    secret: Jg6d2j9GJJ03bMauhsqHpaPePNVr7Lt2
